name: VSCode Extension Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm ci
          npm install --global vsce
          apt-get update && apt-get install -y xvfb
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
      - name: Test extension
        run: DISPLAY=:99.0 npm test
      - name: Build extension
        run: npm run build
